name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install depencencies
      run: sudo apt-get install -y libxkbcommon-dev
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: rust-clippy-check
      uses: actions-rs/clippy-check@v1.0.7
      with:
        token: $GITHUB_TOKEN
        toolchain: stable
        name: clippy
    - name: rust-rustfmt-check
      uses: mbrobbel/rustfmt-check@0.14.0
      with:
        token: $GITHUB_TOKEN
        commit-message: "chore: format"
          
